#!/bin/sh

export PATH=$PATH:$HOME/bin
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export XDG_DESKTOP_DIR="/home/xyh"
export MOZ_USE_XINPUT2=1

xrdb -merge "${HOME}/.Xresources" &
setxkbmap -option ctrl:nocaps &
xbindkeys &
flameshot &
nm-applet &
cbatticon --icon-type symbolic --hide-notification --low-level 15 --critical-level 8 &
~/.wallpapers/random-wallpaper.sh &
# xrandr --rate 165 &
# dunst &

export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11

exec i3
